### ISSUE TITLE
Does it support UILabel?

### ISSUE THREAD

**Issue by zhuhuihuihui** [TapMesh/TMAnimatedTextView#1]
This component has been really helpful. I'm just wondering if it's possible to bring it to the UILabel? Wouldn't that be great?

**Comment by bobwieler** [comment]
The same functionality could be implemented as a UILabel. The labels that we use don't have interactions but it wouldn't be difficult to strip out the unnecessary functionality from this. It's just not something that we need but I encourage you to fork the project and create that functionality.
